zsdos.rel: zsdos-gp.z80 zsdos.lib
	../../bin/zmac --nmnv --zmac -m  --dri -z --rel7 zsdos-gp.z80  -o zsdos.rel -l > zsdos.lst
# use --rel7 and .rel for relative files.
clean:
	rm zsdos.rel zsdos.lst
	
