DEPS=main.c memory.c debug.c disk.c cpu.c terminal.c rz80.h utils.c events.c
emulator: $(DEPS)
	gcc -o emulator $(DEPS) -lm -I ../z80ex-1.1.21/include ../z80ex-1.1.21/z80ex.o ../z80ex-1.1.21/z80ex_dasm.o






